export default function Footer() {
  return (
    <footer>
      <h3>
        <a href="/">REACT LUTHIERS</a>
      </h3>
      <p>
        &copy; Peter Slempers, 2026. Guitar images generated by Google Gemini.
      </p>
      </footer>
  );
}